### ISSUE TITLE
the dataset of key points for fashionai clothing

### ISSUE THREAD

**Issue by tanzf** [HiKapok/tf.fashionAI#3]
Can you send me the dataset of key points for fashionai clothing? The download url have closed,Email:tanzfzb@163.com.     thanks

**Comment by HiKapok** [comment]
@tanzf I'm very sorry, I have just deleted them just serveral days ago because I'm not above rank top 20

**Comment by Houd1ny** [comment]
@tanzf  I`m not sure if it the same dataset, but take a look on https://tianchi.aliyun.com/getStart/information.htm?spm=a2c22.11447509.1154410.2.11e82ffcjIDHVw&raceId=231670
